### Requisição para a raiz da aplicação
http://localhost:5200
// Maria
// - Cadastro de Clientes Pendete
// - Consulta de Clientes Pendete
// - Atualização de Dados de Clientes Pendete
// Manu
// - Exclusão de Clientes Pendete
DELETE http://localhost:5200/api/clientes/excluir/1
DELETE  http://localhost:5200/api/clientes/excluir/2
DELETE http://localhost:5200/api/clientes/excluir/3
DELETE http://localhost:5200/api/clientes/excluir/4
DELETE http://localhost:5200/api/clientes/excluir/5

### Cadastro de Livros
POST http://localhost:5200/api/livros/cadastrar
Content-Type: application/json

{
    "titulo" : "Diario de Um Banana",
    "autor" : "Jeff Kinney",
    "publicação" : 1982,
    "dataDeEmprestimo" : null,
    "dataDeDevolução" : null
}

### Consulta de Livros
GEt http://localhost:5200/api/livros/listar

### Buscar Livros
GEt http://localhost:5200/api/livros/1984
//Guilherme
### Atualização de Dados de Livros
PUT http://localhost:5200/api/atualizar/Dom%20Quixote
Content-Type: application/json

{
    "titulo": "Dom Quixote",
    "autor": "Albert Einstein",
    "anoDePublicacao": 1400,
    "dataDeEmprestimo": null,
    "dataDeDevolucao": null,
    "cliente": null
}



### Exclusão de Livro
DELETE http://localhost:5200/api/deletar/Dom%20Quixote

### - Resgistro De Emprestimo
PUT http://localhost:5200/api/registraEmprestimo/Crime%20e%20Castigo/Ana%20Costa
Content-Type: application/json

{
    "DataDeDevolucao" : "19/10/2024"
}
// Pedro 
// - Registro de Devoluções} precisa colocar a URL da requisição
// - Consulta de Empréstimos Ativos Pendente
// - Reservas de Livros Pendente


