### Requisição para a raiz da aplicação
http://localhost:5200


### - Cadastro de Clientes 
POST http://localhost:5200/api/clientes/cadastrar
Content-Type: application/json

{
    "clienteId": 30,
    "nome": "Carlos Mendes",
    "cpf": "223.255.555-55",
    "dataDeInicio": "2024-10-20"
}



### - Consulta de Clientes 
GET http://localhost:5200/api/clientes/listar

### - Atualização de Dados de Clientes 
PUT http://localhost:5200/api/clientes/atualizar/30
Content-Type: application/json

{
    "nome": "Maria Oliveira Silva",
    "cpf": "123.456.789-00",
    "dataDeInicio": "2022-05-20"
}


### - Exclusão de Clientes 
DELETE http://localhost:5200/api/clientes/excluir/30


### Cadastro de Livros
POST http://localhost:5200/api/livros/cadastrar
Content-Type: application/json

{   

    "titulo": "Teste1",
    "autor": "Teste1",
    "anoDePublicacao": 2002,
    "dataDeEmprestimo": null,
    "dataDeDevolucao": null
}


### Consulta de Livros
GET http://localhost:5200/api/livros/listar

### Buscar Livros
GET http://localhost:5200/api/livros/1984

// Guilherme
### Atualização de Dados de Livros
PUT http://localhost:5200/api/livros/alterar/4adfce8e-c7f4-4acf-867b-f4c493d2a4c3
Content-Type: application/json

{
    "titulo": "Dom Quixote",
    "autor": "Miguel de Cervantes",
    "anoDePublicacao": 1605,
    "dataDeEmprestimo": null,
    "dataDeDevolucao": null,
    "cliente": null
}

### Exclusão de Livro
DELETE http://localhost:5200/api/livros/deletar/f8b9b46f-d416-4c3d-824f-1dd53ca5995b

### - Registro De Empréstimo
POST http://localhost:5200/api/emprestimos/cadastrar
Content-Type: application/json

{
    "IdLivro": 1,
    "ClienteId": 1,
    "DataDeEmprestimo": "2024-10-19",
    "DataDeDevolucao": "2024-10-23"
}


 
### - // - Registro de Devoluções 
POST http://localhost:5200/api/emprestimos/devolver
Content-Type: application/json

{
    "IdLivro": 3
}



### - // - Consulta de Empréstimos Ativos 
GET http://localhost:5200/api/emprestimos/listar




